### ISSUE TITLE
What about ss-common?

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-license#2]
Instead of ss-license only for license generation, what about have a general common template?

**Comment by msclock** [comment]
> a general common template

@huxuan what features does this common template? I just implemented the template with most simple and modular thoughts.

**Comment by huxuan** [comment]
I just mean there may have more common contents like semantic-release related workflow/configuration. But if you mean to have modular sub template, I am totally OK with it.

**Comment by msclock** [comment]
@huxuan I have experimented it with https://github.com/[serious-scaffold/ss-common](https://github.com/serious-scaffold/ss-common) which seems we could assmebly some serious scaffold basic components into this common meta template.

**Comment by huxuan** [comment]
> @huxuan I have experimented it with https://github.com/[serious-scaffold/ss-common](https://github.com/serious-scaffold/ss-common) which seems we could assemble some serious scaffold basic components into this common meta template(ss-license has been assembled).

This is fantastic cool!
